// <auto-generated />
namespace Proba.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedvalidationfordates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedvalidationfordates));
        
        string IMigrationMetadata.Id
        {
            get { return "202009031918061_added-validation-for-dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
